DataDog/dd-bridge-android

buildSrc/src/main/kotlin/com/datadog/gradle/Dependencies.kt
dd-bridge-android/src/main/kotlin/com/datadog/android/bridge/DdBridge.kt
dd-bridge-android/src/main/kotlin/com/datadog/android/bridge/DdLogs.kt
dd-bridge-android/src/main/kotlin/com/datadog/android/bridge/DdRum.kt
dd-bridge-android/src/main/kotlin/com/datadog/android/bridge/DdSdk.kt
dd-bridge-android/src/main/kotlin/com/datadog/android/bridge/DdTrace.kt
dd-bridge-android/src/main/kotlin/com/datadog/android/bridge/internal/BridgeRum.kt
dd-bridge-android/src/main/kotlin/com/datadog/android/bridge/internal/BridgeSdk.kt
dd-bridge-android/src/test/kotlin/com/datadog/android/bridge/internal/BridgeRumTest.kt
dd-bridge-android/transitiveDependencies

Update to version 0.1

---

.gitlab-ci.yml
Dockerfile.gitlab

This PR adds a static analysis to ensure we don't use any non-inclusive language.

Add language check for diversity and inclusion

---

dd-bridge-android/apiSurface
dd-bridge-android/src/main/kotlin/com/datadog/android/bridge/internal/BridgeSdk.kt
dd-bridge-android/src/main/kotlin/com/datadog/android/bridge/internal/NoOpViewTrackingStrategy.kt
dd-bridge-android/src/test/kotlin/com/datadog/android/bridge/internal/BridgeSdkTest.kt
dd-bridge-android/transitiveDependencies

Let the bridge enable/disable native view tracking.
Be able to have both cross platform and native view tracking in cross platform projects

RUMM-1431 Configure native view tracking

---

dd-bridge-android/src/main/kotlin/com/datadog/android/bridge/internal/BridgeSdk.kt
dd-bridge-android/src/test/kotlin/com/datadog/android/bridge/internal/BridgeSdkTest.kt
dd-bridge-android/src/test/kotlin/com/datadog/tools/unit/GenericAssert.kt
dd-bridge-android/transitiveDependencies

Let customer configure long task threshold from cross platform sdks using the `_dd.long_task_threshold` additional attribute

RUMM-1600 Let customer configure long task threshold

---

LICENSE

For now the License is not recognised by Github License detection

Update License to be recognised by Github

---

buildSrc/src/main/kotlin/com/datadog/gradle/Dependencies.kt

Update to version 1.11.0-beta1

---

dd-bridge-android/src/main/kotlin/com/datadog/android/bridge/internal/BridgeSdk.kt
dd-bridge-android/src/test/kotlin/com/datadog/android/bridge/internal/BridgeSdkTest.kt
dd-bridge-android/src/test/kotlin/com/datadog/tools/unit/GenericAssert.kt
dd-bridge-android/transitiveDependencies

Lets customers choose any region supported by the native SDK
This depends on PR [dd-sdk-android#696](https://github.com/DataDog/dd-sdk-android/pull/696) being merged, and version `1.11.0` being released.

RUMM-1569 add support to all regions

---

buildSrc/src/main/kotlin/com/datadog/gradle/Dependencies.kt
dd-bridge-android/build.gradle.kts
dd-bridge-android/src/main/kotlin/com/datadog/android/bridge/internal/BridgeRum.kt
dd-bridge-android/src/main/kotlin/com/datadog/android/bridge/internal/BridgeSdk.kt
dd-bridge-android/src/main/kotlin/com/datadog/android/bridge/internal/ProxyAuthenticator.kt
dd-bridge-android/src/test/kotlin/com/datadog/android/bridge/internal/BridgeSdkTest.kt
dd-bridge-android/src/test/kotlin/com/datadog/android/bridge/internal/ProxyAuthenticatorTest.kt
dd-bridge-android/transitiveDependencies

This change adds the necessary support of the proxy configuration to the bridge which is based on the set of parameters in `additionalConfig`:
```
_dd.proxy.address
_dd.proxy.port
_dd.proxy.type => can be http, https (because iOS has it explicitly) or socks 
_dd.proxy.username
_dd.proxy.password
```
This change depends on the proxy support which was added to the `Datadog SDK` in the PR https://github.com/DataDog/dd-sdk-android/pull/687, but there is no artifact available yet - so compilation of this PR will fail.
The tricky part of this PR is implementation of [okhttp3.Authenticator](https://github.com/square/okhttp/blob/f8fd4d08decf697013008b05ad7d2be10a648358/okhttp/src/main/kotlin/okhttp3/Authenticator.kt) - it is an interface and there is no default implementation available, so …

RUMM-1574: Add an opportunity to configure proxy connection

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

Compared to `0.4.5` contains only a fix for the long task duration extraction (PR https://github.com/DataDog/dd-bridge-android/pull/41).

Bump to version 0.4.6

---

gradle/libs.versions.toml

Update to version 1.11.0-rc1

---

gradle/libs.versions.toml

Update to version 1.11.0

---

.gitlab-ci.yml
dogfood.py

Add a CI script to generate PRs  on dependants repos to ease upgrading them

RUMM-1788 Update dependants repos

---

buildSrc/src/main/kotlin/com/datadog/gradle/config/AndroidConfig.kt

Bump version to 0.5.2

---

gradle/libs.versions.toml

Update to version 1.12.0-alpha1

---

gradle/libs.versions.toml

Update to version 1.12.0-alpha2

---

gradle/libs.versions.toml

Update to version 1.12.0-beta1

---

gradle/libs.versions.toml

Update to version 1.13.0-beta1

---

gradle/libs.versions.toml

Update to version 1.13.0-rc1

---

dd-bridge-android/src/main/kotlin/com/datadog/android/bridge/internal/BridgeSdk.kt
dd-bridge-android/src/test/kotlin/com/datadog/android/bridge/internal/BridgeSdkTest.kt
dd-bridge-android/transitiveDependencies

A brief description of the change being made with this pull request.
What inspired you to submit this pull request?
Anything else we should know when reviewing?
- [ ] Make sure you discussed the feature or bugfix with the maintaining team in an Issue
- [ ] Make sure each commit and the PR mention the Issue number (cf the [CONTRIBUTING](CONTRIBUTING.md) doc)

Pass first party hosts from additional config

---

gradle/libs.versions.toml

Update to version 1.13.0
